# MySQL

spring.datasource.url=jdbc:mysql://localhost:3306/db_intranet_escolar?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Kaiser2702
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# CONFIGURACION JPA / HIBERNATE

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true


# CONFIGURACION JWT

security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
security.jwt.expiration-time=86400000

#puerto

server.port=8080

#angular

cors.allowed-origins=http://localhost:4200